[package]
name = "clichess-server"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
websocket = "0.26.2"
clichess-model = { path = "../clichess-model" }
